# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller

  arm_group_controller:
    type: FollowJointTrajectory
    joints:
      - 1_Joint
      - 2_Joint
      - 3_Joint
      - 4_Joint
      - 5_Joint
      - 6_Joint
    action_ns: follow_joint_trajectory
    default: true
    allowed_start_tolerance: 0.1