# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - 1_Joint
      - 2_Joint
      - 3_Joint
      - 4_Joint
      - 5_Joint
      - 6_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_nonzero_velocity_at_trajectory_end: true
    interpolate_from_desired_state: true
    open_loop_control: true
    allowed_start_tolerance: 0.1


joint_state_broadcaster:
  ros__parameters:
    use_local_topics: true