<?xml version="1.0"?>
<robot name="pinky" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Namespace parameter for multi-robot support -->
    <xacro:arg name="namespace" default=""/>
    <xacro:property name="ns" value="$(arg namespace)"/>
    <xacro:property name="ns_prefix" value="${ns + '/' if ns != '' else ''}"/>

    <xacro:property name="wheel_separation" value="0.11"/>
    <xacro:property name="wheel_diameter" value="0.06"/>
    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.10"/>
    <xacro:property name="chassis_width" value="0.08"/>
    <xacro:property name="chassis_height" value="0.06"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.03"/>
    <xacro:property name="wheel_thickness" value="0.014"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.7"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <link name="${ns_prefix}base_footprint"/>

    <joint name="base_link_fixed_joint" type="fixed">
        <parent link="${ns_prefix}base_footprint"/>
        <child link="${ns_prefix}base_link"/>
        <origin xyz="0 0 ${wheel_diameter/2}" rpy="0 0 0"/>
    </joint>

	<link name="${ns_prefix}base_link"/>
    
     <joint name="chassis_fixed_joint" type="fixed">
        <parent link="${ns_prefix}base_link"/>
        <child link="${ns_prefix}chassis"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

	<link name="${ns_prefix}chassis">
		<visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://pinky_description/meshes/visual/base_link.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="-0.01 0 0.01" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="-0.01 0 0.01" rpy="0 0 0"/>
        </xacro:inertial_box>
	</link>
    
    
    <joint name="caster_fixed_joint" type="fixed">
        <parent link="${ns_prefix}chassis"/>
        <child link="${ns_prefix}caster"/>
        <origin xyz="-0.044 0 -0.02" rpy="0 0 0"/>
    </joint>

	<link name="${ns_prefix}caster">
      <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <joint name="left_wheel_joint" type="fixed">
        <parent link="${ns_prefix}base_link"/>
        <child link="${ns_prefix}left_wheel"/>
        <origin xyz="0 ${wheel_separation/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="${ns_prefix}left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://pinky_description/meshes/visual/wheel.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="right_wheel_joint" type="fixed">
        <parent link="${ns_prefix}base_link"/>
        <child link="${ns_prefix}right_wheel"/>
        <origin xyz="0 ${-1 * wheel_separation/2} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="${ns_prefix}right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://pinky_description/meshes/visual/wheel.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <link name="${ns_prefix}ul_sensor_mount">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://pinky_description/meshes/visual/ul_sensor.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://pinky_description/meshes/collision/ul_sensor.stl" scale="1 1 1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.005 0 0.013" rpy="0 0 0"/>
            <mass value="0.050000"/>
            <inertia ixx="0.000005" ixy="0" ixz="-0.000001" iyy="0.000004" iyz="0" izz="0.000003"/>
        </inertial>
    </link>

    <joint name="ul_sensor_mount_fixed_joint" type="fixed">
        <parent link="${ns_prefix}chassis"/>
        <child link="${ns_prefix}ul_sensor_mount"/>
        <origin xyz="0.038 -0.002 -0.0035" rpy="0 0 0"/>
    </joint>

    <link name="${ns_prefix}ul_sensor_link"/>

    <joint name="ul_sensor_link_fixed_joint" type="fixed">
        <parent link="${ns_prefix}ul_sensor_mount"/>
        <child link="${ns_prefix}ul_sensor_link"/>
        <origin xyz="0.01 0 0" rpy="0 0 0"/>
    </joint>

    <link name="${ns_prefix}front_camera_mount">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://pinky_description/meshes/visual/camera.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://pinky_description/meshes/collision/camera.stl" scale="1 1 1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.005 0 0.013" rpy="0 0 0"/>
            <mass value="0.050000"/>
            <inertia ixx="0.000005" ixy="0" ixz="-0.000001" iyy="0.000004" iyz="0" izz="0.000003"/>
        </inertial>
    </link>

    <joint name="front_camera_mount_fixed_joint" type="fixed">
        <parent link="${ns_prefix}chassis"/>
        <child link="${ns_prefix}front_camera_mount"/>
        <origin xyz="0.05 -0.001 0.028" rpy="0 0 0"/>
    </joint>

    <link name="${ns_prefix}camera_link"/>

    <joint name="camera_link_fixed_joint" type="fixed">
        <parent link="${ns_prefix}front_camera_mount"/>
        <child link="${ns_prefix}camera_link"/>
        <origin xyz="0.001 0 0.003" rpy="-${pi/2} 0 -${pi/2}"/>
    </joint>

    <link name="${ns_prefix}lidar_lidar_mount">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://pinky_description/meshes/visual/lidar.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://pinky_description/meshes/collision/lidar.stl" scale="1 1 1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.007 0 0.025" rpy="0 0 0"/>
            <mass value="0.110"/>
            <inertia ixx="0.000058" ixy="0" ixz="0.000005" iyy="0.000099" iyz="0" izz="0.000103"/>
        </inertial>
    </link>

    <joint name="lidar_mount_fixed_joint" type="fixed">
        <parent link="${ns_prefix}chassis"/>
        <child link="${ns_prefix}lidar_lidar_mount"/>
        <origin xyz="0 0 0.042" rpy="0 0 0"/>
    </joint>

    <link name="${ns_prefix}laser_link"/>

    <joint name="laser_link_fixed_joint" type="fixed">
        <parent link="${ns_prefix}lidar_lidar_mount"/>
        <child link="${ns_prefix}laser_link"/>
        <origin xyz="0.0 0 0.03" rpy="0 0 ${pi}"/>
    </joint>

    <link name="${ns_prefix}imu_link"/>
    
    <joint name="imu_link_joint" type="fixed">
        <parent link="${ns_prefix}chassis"/>
        <child link="${ns_prefix}imu_link"/>
        <origin xyz="0 0 0.03" rpy="0 0 0"/>
    </joint>

    <joint name="pinky_bag_fixed_joint" type="fixed">
        <parent link="${ns_prefix}chassis"/>
        <child link="${ns_prefix}pinky_bag"/>
        <!-- chassis 기준 뒤쪽으로 0.25m, 높이 0.05m 정도 -->
        <origin xyz="-0.1085 0 0.018" rpy="0 0 0"/>
    </joint>
    <link name="${ns_prefix}pinky_bag">
        <visual>
            <origin xyz="0.0535 0.0575 -0.0035" rpy="0 0 3.14159"/>
            <geometry>
                <mesh filename="package://pinky_description/meshes/visual/pinky_bag.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="pinky_bag_material">
                <color rgba="0.8 0.2 0.2 1"/>       
            </material>   
        </visual>
        <collision>
            <origin xyz="0.0535 0.0575 -0.0035" rpy="0 0 3.14159"/>
            <geometry>
                <mesh filename="package://pinky_description/meshes/collision/pinky_bag.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.05"/> <!-- kg 단위, 대략 설정 -->
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.001" iyy="0.001" izz="0.001"
                    ixy="0.0" ixz="0.0" iyz="0.0"/>
        </inertial>
    </link>    
</robot>